FROM openresty/openresty:alpine

WORKDIR /home/app
RUN apk add --no-cache git cmake make gcc g++ jansson-dev openssl-dev 


COPY ./nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY ./lib/resty/* /usr/local/openresty/lualib/resty/

RUN git clone https://github.com/benmcollins/libjwt.git
RUN mkdir libjwt/build
RUN cd libjwt/build && cmake ..
RUN cd libjwt/build && make && make install


EXPOSE 8888
CMD ["openresty", "-g", "daemon off;"]