services:
  nginx:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8888:8888"
    volumes:
      - ./tokens:/usr/share/tokens
  memory_leak:
    profiles:
      - memory_leak
    build:
      context: .
      dockerfile: ./.memory_leak/Dockerfile