name: LuaJIT Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LuaJIT and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit luarocks

      - name: Install luaunit
        run: sudo luarocks install luaunit

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run LuaJIT tests
        run: make test
      
      - name: Run Golang E2E tests
        run: make test-e2e
